#!/bin/bash

set -eu -o pipefail

DASHBOARDS_VERSION=2.4.1

docker build \
       --build-arg DASHBOARDS_VERSION=$DASHBOARDS_VERSION \
       -t phatality-build .
id=$(docker run -d --entrypoint /bin/sleep phatality-build:latest 3600)
trap "docker rm -f $id" EXIT
docker cp $id:/src/OpenSearch-Dashboards/plugins/phatality/build/phatality-$DASHBOARDS_VERSION.zip deploy/
