#!/bin/bash

set -eu -o pipefail

if [ $# -ne 1 ]; then
  cat <<EOF
Usage: $0 DASHBOARDS_VERSION

Example: $0 1.2.3
EOF
  exit 1
fi

DASHBOARDS_VERSION="$1"

docker build \
       --build-arg DASHBOARDS_VERSION=$DASHBOARDS_VERSION \
       -t phatality-build .
id=$(docker run -d --entrypoint /bin/sleep phatality-build:latest 3600)
trap "docker rm -f $id" EXIT
docker cp $id:/src/OpenSearch-Dashboards/plugins/phatality/build/phatality-$DASHBOARDS_VERSION.zip deploy/
ls -l deploy/phatality-$DASHBOARDS_VERSION.zip
